name: manage-azure-policy-7dfe3cb1
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Add_diagnostic_setting_on_blob_level_-_shiwei2_0ca1fce5-967f-4ac5-8e6a-192f7367dae1/**'
#      - .github/workflows/manage-azure-policy-7dfe3cb1.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_7dfe3cb1}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Add_diagnostic_setting_on_blob_level_-_shiwei2_0ca1fce5-967f-4ac5-8e6a-192f7367dae1/**
