name: manage-azure-policy-530e19dc
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/shiweitesting_only_apply_on_Windows_VMs_07c31acf-bfb4-4aa4-b0c2-13220b540788/**'
#      - .github/workflows/manage-azure-policy-530e19dc.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_530e19dc}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/shiweitesting_only_apply_on_Windows_VMs_07c31acf-bfb4-4aa4-b0c2-13220b540788/**
